# Step 1: Fix database
FIX_DATABASE.bat

# Step 2: In phpMyAdmin, run this SQL:
CREATE DATABASE IF NOT EXISTS hello_db;
USE hello_db;
CREATE TABLE IF NOT EXISTS new_db (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
